// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromptApi.Models;

namespace PromptApi.Migrations
{
    [DbContext(typeof(PromptContext))]
    [Migration("20200401225231_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PromptApi.Models.Prompt", b =>
                {
                    b.Property<int>("PromptId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthorName");

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<string>("Journal")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("PromptId");

                    b.ToTable("Prompts");

                    b.HasData(
                        new
                        {
                            PromptId = 2,
                            AuthorName = "Dave",
                            Content = "Dave had a story, but then again, so does everyone",
                            Journal = "Daves Journal",
                            Title = "Dave's Story"
                        },
                        new
                        {
                            PromptId = 1,
                            AuthorName = "Jimmyboy",
                            Content = "Jimmy is a dude, pretty cool dude, but is not a template writing-prompt, funny how that works",
                            Journal = "Jimmy Journal",
                            Title = "Matilda"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
